// <auto-generated />
using LoanManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanManagementSystem.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230415105858_InitforWaterfallServices")]
    partial class InitforWaterfallServices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoanManagementSystem.Models.Accounts", b =>
                {
                    b.Property<int>("aID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("aID"), 1L, 1);

                    b.Property<string>("account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("aID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LeadPrice", b =>
                {
                    b.Property<int>("lpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lpId"), 1L, 1);

                    b.Property<double>("ETAA2000")
                        .HasColumnType("float");

                    b.Property<double>("ETAA3000")
                        .HasColumnType("float");

                    b.Property<double>("ETAA4000")
                        .HasColumnType("float");

                    b.Property<double>("ETAA5000")
                        .HasColumnType("float");

                    b.Property<double>("ETAB1999")
                        .HasColumnType("float");

                    b.HasKey("lpId");

                    b.ToTable("LeadPrices");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Roles", b =>
                {
                    b.Property<int>("rId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rId"), 1L, 1);

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.ScoreCard", b =>
                {
                    b.Property<int>("scID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("scID"), 1L, 1);

                    b.Property<int>("acntId")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<double>("maxIncome")
                        .HasColumnType("float");

                    b.Property<double>("maxLoanamt")
                        .HasColumnType("float");

                    b.Property<double>("minIncome")
                        .HasColumnType("float");

                    b.Property<double>("minLoanamt")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("routingBlcklst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stateId")
                        .HasColumnType("int");

                    b.Property<string>("zipcodeBlcklst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("scID");

                    b.HasIndex("acntId");

                    b.HasIndex("stateId");

                    b.ToTable("ScoreCards");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.ServicesforWaterfall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("srvcName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("servicesforWaterfalls");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.States", b =>
                {
                    b.Property<int>("sID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sID"), 1L, 1);

                    b.Property<string>("stateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sID");

                    b.ToTable("States");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("activeStatus")
                        .HasColumnType("bit");

                    b.Property<string>("emailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Waterfall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("wtrflName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Waterfalls");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.WaterfallService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrdrPull")
                        .HasColumnType("int");

                    b.Property<bool>("activeStatus")
                        .HasColumnType("bit");

                    b.Property<int>("srWID")
                        .HasColumnType("int");

                    b.Property<int>("wID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("srWID");

                    b.HasIndex("wID");

                    b.ToTable("WaterfallServices");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.ScoreCard", b =>
                {
                    b.HasOne("LoanManagementSystem.Models.Accounts", "Accounts")
                        .WithMany()
                        .HasForeignKey("acntId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagementSystem.Models.States", "States")
                        .WithMany()
                        .HasForeignKey("stateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("States");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.User", b =>
                {
                    b.HasOne("LoanManagementSystem.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.WaterfallService", b =>
                {
                    b.HasOne("LoanManagementSystem.Models.ServicesforWaterfall", "ServicesforWaterfall")
                        .WithMany()
                        .HasForeignKey("srWID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagementSystem.Models.Waterfall", "Waterfall")
                        .WithMany()
                        .HasForeignKey("wID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicesforWaterfall");

                    b.Navigation("Waterfall");
                });
#pragma warning restore 612, 618
        }
    }
}
